import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Header } from '@/components/header';
import { Providers } from './providers';
import { Toaster } from 'sonner';
import Illustration from '@/components/ui/illustration';
import './globals.css';

const robotoSans = Roboto({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'TuneReveal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${robotoSans.className} dark antialiased w-full px-4 mx-auto max-w-[1140px] relative flex flex-col overflow-hidden`}
      >
        <Illustration />
        <Header />
        <Providers>{children}</Providers>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
