import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Header } from '@/components/header';
import { Providers } from './providers';
import { Toaster } from 'sonner';
import Illustration from '@/components/ui/illustration';
import './globals.css';

const robotoSans = Roboto({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'TuneReveal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={`${robotoSans.className} dark antialiased w-full px-4 mx-auto h-screen overflow-x-hidden`}>
        <div className="w-full max-w-[1140px] mx-auto relative flex flex-col">
          <Illustration />
          <Header />
          <Providers>{children}</Providers>
        </div>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
