services:
  node:
    build: ./node
    ports:
      - '3333:3333'
    environment:
      - PYTHON_API_URL=${PYTHON_API_URL}
    depends_on:
      - python

  python:
    build: ./python
    ports:
      - '5000:5000'
    environment:
      - PROXY_URL=${PROXY_URL}
      - COOKIES_B64=${COOKIES_B64}
