services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PYTHON_API_URL=${PYTHON_API_URL}
    depends_on:
      - python-service

  python-service:
    build: ./python
    ports:
      - "5000:5000"
    environment:
      - PROXY_URL=${PROXY_URL}
      - COOKIES_B64=${COOKIES_B64}