import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const robotoSans = Roboto({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'TuneReveal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.className} antialiased w-full max-w-[1140px] px-4 mx-auto`}>
        <header className="h-20 flex items-center justify-end">
          <p className="font-medium text-sm">
            Built by{' '}
            <Link href="https://duardodev.vercel.app/en" target="_blank" className="underline">
              duardodev
            </Link>
          </p>
        </header>

        {children}
      </body>
    </html>
  );
}
